src/questionvault/apps/questions/urls.py
from django.conf.urls import patterns, url

from views import edit_question

urlpatterns = patterns('',
                       url('new', edit_question, name="new")
                )

src/questionvault/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project_template.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
            url(r'^$', TemplateView.as_view(template_name="landing.html")),
            url(r'^q/', include('questionvault.apps.questions.urls', namespace='questions')),
            url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

src/questionvault/apps/questions/models.py
from django.db import models


class Question(models.Model):
    """
    Basic text-based question model
    """

    # TODO we will eventually want richer question formats
    text = models.TextField(verbose_name="question text")
    title = models.CharField(max_length=1000, verbose_name="question title")

    def __unicode__(self):
        return self.title + ": " + self.text


class Answer(models.Model):
    """
    Basic text-based answer option for multiple choice questions
    """    
    question = models.ForeignKey(Question)
    text = models.TextField(max_length=1000, verbose_name="displayed answer")
    explanation = models.TextField(verbose_name="Explanation")
    is_correct = models.BooleanField(default=False)

    def __unicode__(self):
        ret_txt = ""
        if self.is_correct:
            ret_txt += "[correct]   :"
        else:
            ret_txt += "[incorrect] :"
        return ret_txt + self.text + "(explanation: " + self.explanation + ")\n"
    

src/questionvault/apps/questions/forms.py
import pdb

from django import forms

from models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'text']

class AnswerFormSet(forms.models.BaseInlineFormSet):
    def clean(self):
        correct_count = sum([form.cleaned_data.has_key('is_correct') and form.cleaned_data['is_correct'] for form in self.forms])
        if correct_count != 1:
            raise forms.ValidationError('Exactly one answer must be marked as correct')

src/questionvault/apps/questions/views.py
import pdb

from django.shortcuts import render_to_response
from django.http import HttpResponse
from django.template import RequestContext
from django import forms

from models import Question, Answer
from forms import QuestionForm, AnswerFormSet

# view handling groked from http://stackoverflow.com/questions/18755909/django-multiple-modelforms-with-the-same-model-and-foreignkeys
def edit_question(request):
    AnswerFormset = forms.models.inlineformset_factory(
         Question, Answer, formset=AnswerFormSet, extra=4, max_num=4)
#    question = Question()
    if request.method == 'POST':
        question = Question()
        question_form = QuestionForm(request.POST, instance=question)
        answer_formset = AnswerFormset(request.POST, instance=question)
        
        # Check these separately to avoid short-circuiting
        question_valid = question_form.is_valid()
        answer_valid = answer_formset.is_valid()
        
        if question_valid and answer_valid:
            question_form.save()
            answer_formset.save()
            return HttpResponse("<html><body>question accepted <--TODO something sensible</body></html>") # TODO redirect to something worthwhile

    elif request.method == 'GET':
        answer_formset = AnswerFormset()
        question_form = QuestionForm()
    elif request.method:
        return HttpResponse(status=405)

    return render_to_response("question_edit.html",
                              {"formset": answer_formset, "question_form": question_form},
                              context_instance=RequestContext(request))

src/questionvault/apps/questions/templates/question_edit.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extend-css %}
<link href="{% static "css/lib/ionicons.css"%}" type="text/css" rel="stylesheet" />
<link href="{% static "scss/qna.scss"%}" type="text/x-scss" rel="stylesheet" />
{% endblock %}

{% block extend-js %}
<script src="{% static "js/qedit.js" %}"></script>
{% endblock %}

{% block main %}
<form action="" method="POST" id="question_form">{% csrf_token %}
  <section id="question-title">
    <label for="id_title">
      Title:
    </label>
    {{ question_form.title }}
  </section>

  <section id="errors">
    <!-- FIXME -->
  {% for error in formset.errors %}
    <div>
      {{ error }}
    </div>
  {% endfor %}
  </section>

  <section id="question-area">
      <h2> Question </h2>
      {{ question_form.text }}
  </section>

  <section id="answer-area">
    <h2> Answers </h2>
    {{formset.management_form}}
    {% for form in formset %}
    <div class="answer">

      <div class="answer-selector">
        {{ form.is_correct }}
      </div>

      <div class="answer-content">
        <div class="answer-text">
          {{ form.text.label }}
          {{ form.text }}
        </div>

        <div class="explanation">
          <div class="collapse-label">
            {{ form.explanation.label }} (recommended) <i class="icon ion-ios7-arrow-down"></i> <i class="icon ion-ios7-arrow-forward"></i>
          </div>
          {{ form.explanation }}
        </div>
      </div>
    </div>

    {% endfor %}
    <div class="form_buttons">
      <button type="submit" name="confirm" id="confirm">
        <span>Submit</span>
      </button>
    </div>
  </section>
</form>
{% endblock %}

src/templates/base.html
{% load staticfiles %}
{% load compress %}

<!doctype html>
<html xml:lang="{{ LANGUAGE_CODE|default:"en" }}" lang="{{ LANGUAGE_CODE|default:"en" }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="keywords" content="{% block meta-keywords %}{% endblock %}" />
    <meta name="description" content="{% block meta-description %}{% endblock %}" />

    <title>{% block headtitle %}Template Title{% endblock %}</title>

    <meta property="og:type" content="{% block og-type %}website{% endblock %}" />
    {% compress css %}

    {% block base-css %}
    <link href="{% static "css/lib/reset-min.css"%}" rel="stylesheet" />
    <link href="{% static "scss/base.scss"%}" type="text/x-scss" rel="stylesheet" />
    {% endblock %}

    {% block extend-css %}
    {% endblock %}

    {% endcompress %}

<!--[if lt IE 9]>
<script src="{% static "js/lib/html5shiv.js" %}"></script>
<![endif]-->
  </head>

  <body id="{% block bodyid %}page{% endblock %}" class="{% block bodyclass %}default{% endblock %}" itemscope itemtype="http://schema.org/WebPage">
    <div id="wrapper">

      <header id="top">
      </header>

      <section id="content">
        <div id="main">
          {% block main %}{% endblock %}
        </div>
      </section>

      <footer id="bottom">
      </footer>
    </div>

    {% compress js %}

    {% block js %}
    <script src="{% static "js/lib/jquery-1.10.2.js" %}"></script>
    {% endblock %}

    {% block extend-js %}{% endblock %}

    {% endcompress %}
  </body>
</html>

src/templates/landing.html
{% extends "base.html" %}

{% block main %}
Hello World!
{% endblock %}